version: "3.9"

services:
  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:1.8.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
        #      - LOG_LEVEL=INFO
    volumes:
      - ls-data:/label-studio/data:rw
    command: label-studio-uwsgi

  db:
    image: postgres:11.5
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ls-postgres-data:/var/lib/postgresql/data

  db-backup:
    image: tiredofit/db-backup:3.9.12
    volumes:
      - /data/config/labelstudio/db:/backup
      - ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=America/New_York
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=
      - DB_DUMP_BEGIN=+1
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=2880
      - CONTAINER_ENABLE_MONITORING=FALSE

  vectordb:
    image: ankane/pgvector
    hostname: vectordb
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - vdb:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15692:15692"   # prometheus exporter

  ingest:
    image: iank1/catflow_ingest:v0.2.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:5057:5057"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RABBITMQ_EXCHANGE=${CATFLOW_RABBITMQ_EXCHANGE}
      - AWS_ACCESS_KEY_ID=${CATFLOW_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${CATFLOW_AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${CATFLOW_S3_ENDPOINT_URL}
      - AWS_BUCKETNAME=${CATFLOW_AWS_BUCKETNAME}

  videosplit:
    image: iank1/catflow_service_videosplit:v0.3.0
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${CATFLOW_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${CATFLOW_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${CATFLOW_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${CATFLOW_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${CATFLOW_AWS_BUCKETNAME}

  inference-svc:
    image: iank1/catflow_service_inference:v0.3.2
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${CATFLOW_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${CATFLOW_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${CATFLOW_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${CATFLOW_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${CATFLOW_AWS_BUCKETNAME}
      - CATFLOW_MODEL_NAME=${CATFLOW_MODEL_NAME}
      - CATFLOW_MODEL_THRESHOLD=${CATFLOW_MODEL_THRESHOLD}
    volumes:
      - ./liquid_robot_2568_best.pt:/app/liquid_robot_2568_best.pt

  filter:
    image: iank1/catflow_service_filter:v0.1.3
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - vectordb
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${CATFLOW_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${CATFLOW_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${CATFLOW_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${CATFLOW_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${CATFLOW_AWS_BUCKETNAME}
      - CATFLOW_PG_HOST=${CATFLOW_PG_HOST}
      - CATFLOW_PG_DBNAME=${CATFLOW_PG_DBNAME}
      - CATFLOW_PG_USER=${CATFLOW_PG_USER}
      - CATFLOW_PG_PASSWORD=${CATFLOW_PG_PASSWORD}
      - CATFLOW_PG_PORT=${CATFLOW_PG_PORT}
      - CATFLOW_VDB_THRESHOLD=${CATFLOW_VDB_THRESHOLD}

  taskcreator:
    image: iank1/catflow_service_taskcreator:v0.1.4
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${CATFLOW_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${CATFLOW_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${CATFLOW_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${CATFLOW_S3_ENDPOINT_URL}
      - CATFLOW_S3_WEB_URL=${CATFLOW_S3_WEB_URL}
      - CATFLOW_TASK_CREATION_PROB=${CATFLOW_TASK_CREATION_PROB}
      - CATFLOW_AWS_BUCKET_NAME=${CATFLOW_AWS_BUCKETNAME}
      - CATFLOW_LS_BUCKET_NAME=${CATFLOW_LS_BUCKET_NAME}
      - CATFLOW_LS_BASE_URL=${CATFLOW_LS_BASE_URL}
      - CATFLOW_LS_PROJECT_ID=${CATFLOW_LS_PROJECT_ID}
      - CATFLOW_LS_AUTH_TOKEN=${CATFLOW_LS_AUTH_TOKEN}

  detector:
    image: iank1/catflow_service_detector:v0.1.2
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${CATFLOW_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${CATFLOW_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${CATFLOW_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${CATFLOW_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${CATFLOW_AWS_BUCKETNAME}
      - CATFLOW_SIGNAL_URL=${CATFLOW_SIGNAL_URL}
      - CATFLOW_SIGNAL_SOURCE=${CATFLOW_SIGNAL_SOURCE}
      - CATFLOW_SIGNAL_DEST=${CATFLOW_SIGNAL_DEST}
      - CATFLOW_DETECTOR_CLASSES=${CATFLOW_DETECTOR_CLASSES}

volumes:
  vdb:
  ls-data:
    external: true
  ls-postgres-data:
    external: true
