version: "3.9"

services:
  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
        #      - LOG_LEVEL=INFO
    volumes:
      - /data/labelstudio/mydata:/label-studio/data:rw
    command: label-studio-uwsgi

  db:
    image: postgres:11.5
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /data/labelstudio/postgres-data:/var/lib/postgresql/data
      - /data/labelstudio/deploy/pgsql/certs:/var/lib/postgresql/certs:ro

  frameextractor:
    image: iank1/frameextractor:v0.5.5
    restart: unless-stopped
    depends_on:
      - vectordb
    ports:
      - "127.0.0.1:5053:5053"
    volumes:
      - ./uncertain_hummingbird_2281_best.pt:/app/uncertain_hummingbird_2281_best.pt
      - ./frameextractor.ini:/app/frameextractor.ini

  vectordb:
    image: ankane/pgvector
    hostname: vectordb
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - /data/vectordb/postgres-data:/var/lib/postgresql/data

  inference:
    image: iank1/catflow_inference:v0.2.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:5054:5054"
    environment:
      - YOLO_THRESHOLD=${YOLO_THRESHOLD}
      - YOLO_WEIGHTS=${YOLO_WEIGHTS}
    volumes:
      - ./uncertain_hummingbird_2281_best.pt:/app/uncertain_hummingbird_2281_best.pt


  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"

  ingest:
    image: iank1/catflow_ingest:v0.2.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:5057:5057"
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - RABBITMQ_EXCHANGE=${INGEST_RABBITMQ_EXCHANGE}
      - AWS_ACCESS_KEY_ID=${INGEST_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${INGEST_AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${INGEST_S3_ENDPOINT_URL}
      - AWS_BUCKETNAME=${INGEST_AWS_BUCKETNAME}

  videosplit:
    image: iank1/catflow_service_videosplit:v0.3.0
    restart: unless-stopped
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${INGEST_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${INGEST_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${INGEST_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${INGEST_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${INGEST_AWS_BUCKETNAME}

  inference-svc:
    image: iank1/catflow_service_inference:v0.3.0
    restart: unless-stopped
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${INGEST_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${INGEST_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${INGEST_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${INGEST_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${INGEST_AWS_BUCKETNAME}
      - CATFLOW_MODEL_NAME=${CATFLOW_MODEL_NAME}
      - CATFLOW_MODEL_THRESHOLD=${CATFLOW_MODEL_THRESHOLD}
    volumes:
      - ./uncertain_hummingbird_2281_best.pt:/app/uncertain_hummingbird_2281_best.pt

  filter:
    image: iank1/catflow_service_filter:v0.1.2
    restart: unless-stopped
    environment:
      - CATFLOW_AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - CATFLOW_AMQP_EXCHANGE=${INGEST_RABBITMQ_EXCHANGE}
      - CATFLOW_AWS_ACCESS_KEY_ID=${INGEST_AWS_ACCESS_KEY_ID}
      - CATFLOW_AWS_SECRET_ACCESS_KEY=${INGEST_AWS_SECRET_ACCESS_KEY}
      - CATFLOW_S3_ENDPOINT_URL=${INGEST_S3_ENDPOINT_URL}
      - CATFLOW_AWS_BUCKET_NAME=${INGEST_AWS_BUCKETNAME}
      - CATFLOW_PG_HOST=${CATFLOW_PG_HOST}
      - CATFLOW_PG_DBNAME=${CATFLOW_PG_DBNAME}
      - CATFLOW_PG_USER=${CATFLOW_PG_USER}
      - CATFLOW_PG_PASSWORD=${CATFLOW_PG_PASSWORD}
      - CATFLOW_PG_PORT=${CATFLOW_PG_PORT}
      - CATFLOW_VDB_THRESHOLD=${CATFLOW_VDB_THRESHOLD}
